stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/students.csv
    outs:
      - data/processed/cleaned.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/cleaned.csv
    outs:
      - models/model.pkl
